export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'

export const INIT_LOGIN = 'INIT_LOGIN'
export const HIDE_LOADING = 'HIDE_LOADING'

export const CONFIRM_EMAIL_REQUEST = 'CONFIRM_EMAIL_REQUEST'
export const CONFIRM_EMAIL_SUCCESS = 'CONFIRM_EMAIL_SUCCESS'
export const CONFIRM_EMAIL_FAILURE = 'CONFIRM_EMAIL_FAILURE'

export const RESET_PASSWORD_CONFIRM_REQUEST = 'RESET_PASSWORD_CONFIRM_REQUEST'
export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS'
export const RESET_PASSWORD_CONFIRM_FAILURE = 'RESET_PASSWORD_CONFIRM_FAILURE'

export const UPDATE_DELIVERY_ADDRESS_REQUEST = 'UPDATE_DELIVERY_ADDRESS_REQUEST'
export const UPDATE_DELIVERY_ADDRESS_SUCCESS = 'UPDATE_DELIVERY_ADDRESS_SUCCESS'
export const UPDATE_DELIVERY_ADDRESS_FAILURE = 'UPDATE_DELIVERY_ADDRESS_FAILURE'

export const USER_AUTHORIZE_REQUEST = 'USER_AUTHORIZE_REQUEST'
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST'

export const PARTNER_LOAD_REQUEST = 'PARTNER_LOAD_REQUEST'
export const PARTNER_LOAD_SUCCESS = 'PARTNER_LOAD_SUCCESS'
export const PARTNER_LOAD_FAILURE = 'PARTNER_LOAD_FAILURE'

export const SUPPLIER_LOAD_REQUEST = 'SUPPLIER_LOAD_REQUEST'
export const SUPPLIER_LOAD_SUCCESS = 'SUPPLIER_LOAD_SUCCESS'
export const SUPPLIER_LOAD_FAILURE = 'SUPPLIER_LOAD_FAILURE'

export const PARTNER_ORDER_EVENT_REQUEST = 'PARTNER_ORDER_EVENT_REQUEST'
export const PARTNER_ORDER_EVENT_SUCCESS = 'PARTNER_ORDER_EVENT_SUCCESS'
export const PARTNER_ORDER_EVENT_FAILURE = 'PARTNER_ORDER_EVENT_FAILURE'

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE'

export const LOAD_ORDER_BY_QRCODE_REQUEST = 'LOAD_ORDER_BY_QRCODE_REQUEST'
export const LOAD_ORDER_BY_QRCODE_SUCCESS = 'LOAD_ORDER_BY_QRCODE_SUCCESS'
export const LOAD_ORDER_BY_QRCODE_FAILURE = 'LOAD_ORDER_BY_QRCODE_FAILURE'

export const UPLOAD_PICTURE_REQUEST = 'UPLOAD_PICTURE_REQUEST'
export const UPLOAD_PICTURE_SUCCESS = 'UPLOAD_PICTURE_SUCCESS'
export const UPLOAD_PICTURE_FAILURE = 'UPLOAD_PICTURE_FAILURE'

export const ADD_EVENT_REQUEST = 'ADD_EVENT_REQUEST'
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS'
export const ADD_EVENT_FAILURE = 'ADD_EVENT_FAILURE'

export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST'
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS'
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE'

export const ADD_BOOKING_REQUEST = 'ADD_BOOKING_REQUEST'
export const ADD_BOOKING_SUCCESS = 'ADD_BOOKING_SUCCESS'
export const ADD_BOOKING_FAILURE = 'ADD_BOOKING_FAILURE'

export const ADD_QUESTION_REQUEST = 'ADD_QUESTION_REQUEST'
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS'
export const ADD_QUESTION_FAILURE = 'ADD_QUESTION_FAILURE'

export const ADD_ANSWER_REQUEST = 'ADD_ANSWER_REQUEST'
export const ADD_ANSWER_SUCCESS = 'ADD_ANSWER_SUCCESS'
export const ADD_ANSWER_FAILURE = 'ADD_ANSWER_FAILURE'

export const MARK_AS_READ_ORDER_REQUEST = 'MARK_AS_READ_ORDER_REQUEST'
export const MARK_AS_READ_ORDER_SUCCESS = 'MARK_AS_READ_ORDER_SUCCESS'
export const MARK_AS_READ_ORDER_FAILURE = 'MARK_AS_READ_ORDER_FAILURE'

export const ADD_TRACKING_NUMBER_REQUEST = 'ADD_TRACKING_NUMBER_REQUEST'
export const ADD_TRACKING_NUMBER_SUCCESS = 'ADD_TRACKING_NUMBER_SUCCESS'
export const ADD_TRACKING_NUMBER_FAILURE = 'ADD_TRACKING_NUMBER_FAILURE'

export const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST'
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS'
export const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE'

export const DELETE_BOOKING_ITEM_REQUEST = 'DELETE_BOOKING_ITEM_REQUEST'
export const DELETE_BOOKING_ITEM_SUCCESS = 'DELETE_BOOKING_ITEM_SUCCESS'
export const DELETE_BOOKING_ITEM_FAILURE = 'DELETE_BOOKING_ITEM_FAILURE'

export const GET_USER_LIST_REQUEST = 'GET_USER_LIST_REQUEST'
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS'
export const GET_USER_LIST_FAILURE = 'GET_USER_LIST_FAILURE'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE'

export const INVITE_NEW_USER_REQUEST = 'INVITE_NEW_USER_REQUEST'
export const INVITE_NEW_USER_SUCCESS = 'INVITE_NEW_USER_SUCCESS'
export const INVITE_NEW_USER_FAILURE = 'INVITE_NEW_USER_FAILURE'

export const CHANGE_PERMISSION_REQUEST = 'CHANGE_PERMISSION_REQUEST'
export const CHANGE_PERMISSION_SUCCESS = 'CHANGE_PERMISSION_SUCCESS'
export const CHANGE_PERMISSION_FAILURE = 'CHANGE_PERMISSION_FAILURE'

export const RESET_APP_REQUEST = 'RESET_APP_REQUEST'

export const DEACTIVATE_USER_REQUEST = 'DEACTIVATE_USER_REQUEST'
export const DEACTIVATE_USER_SUCCESS = 'DEACTIVATE_USER_SUCCESS'
export const DEACTIVATE_USER_FAILURE = 'DEACTIVATE_USER_FAILURE'

export const REFRESH_TOKEN = 'REFRESH_TOKEN'
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS'
export const REFRESH_TOKEN_FAILURE = 'REFRESH_TOKEN_FAILURE'

export const ADD_TAG_REQUEST = 'ADD_TAG_REQUEST'
export const ADD_TAG_SUCCESS = 'ADD_TAG_SUCCESS'
export const ADD_TAG_FAILURE = 'ADD_TAG_FAILURE'

export const DELETE_TAG_REQUEST = 'DELETE_TAG_REQUEST'
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS'
export const DELETE_TAG_FAILURE = 'DELETE_TAG_FAILURE'

export const DELETE_TAGBYID_REQUEST = 'DELETE_TAGBYID_REQUEST'
export const DELETE_TAGBYID_SUCCESS = 'DELETE_TAGBYID_SUCCESS'
export const DELETE_TAGBYID_FAILURE = 'DELETE_TAGBYID_FAILURE'

export const UPDATE_TAGBYID_REQUEST = 'UPDATE_TAGBYID_REQUEST'
export const UPDATE_TAGBYID_SUCCESS = 'UPDATE_TAGBYID_SUCCESS'
export const UPDATE_TAGBYID_FAILURE = 'UPDATE_TAGBYID_FAILURE'

export const GET_TAGS_REQUEST = 'GET_TAGS_REQUEST'
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS'
export const GET_TAGS_FAILURE = 'GET_TAGS_FAILURE'

export const LOADING_FINISH = 'LOADING_FINISH'
export const LOADING_START = 'LOADING_START'

export const NEW_REGISTRATION_LINK_REQUEST = 'NEW_REGISTRATION_LINK_REQUEST'
export const NEW_REGISTRATION_LINK_SUCCESS = 'NEW_REGISTRATION_LINK_SUCCESS'
export const NEW_REGISTRATION_LINK_FAILURE = 'NEW_REGISTRATION_LINK_FAILURE'
